<?php

/**
 * @file
 * Variable integration for the Publications Subscription module.
 */


/**
 * Implements hook_help().
 */
function pubsub_help($path, $arg) {
  switch ($path) {
    case 'admin/help#pubsub':
      print t('Yataaa');
      break;
  }
}

/**
 * Implements hook_schema().
 *
 * Schema Reference: https://drupal.org/node/146939
 * Data types: https://drupal.org/node/159605
 *
 */
function pubsub_schema() {
  // @TODO: Vérifier si la table existe dans la BDD
  $schema = array();

  $schema['pubsub'] = array(
    'description' => t('Store subscribers email'),
    'fields' => array(
      'emid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not_null' => TRUE
      ),
      'email_address' => array(
        'type' => 'varchar',
        'length' => 80,
        'not_null' => TRUE
      ),
      'created_at' => array(
        //'type' => 'int',
        'mysql_type' => 'DATETIME',
        'pgsql_type' => 'timestamp without time zone',
        'not_null' => TRUE
      ),
    ),
    'unique keys' => array( 'name' => array('email_address')),
    'primary key' => array('emid'),
  );

  return $schema;
}

/**
 * Implements hook_install().
 */
function pubsub_install() {
}

/**
 * Implements hook_uninstall().
 */
function pubsub_uninstall() {
  //@TODO suppression des tables installés?
}

